# .github/workflows/automerge.yml
name: Automerge safe deps
on: pull_request
permissions: contents: write, pull-requests: write
jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          target: minor
          merge-method: squash
