name: CI‑CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      deploy-prod:
        description: "Déployer en production ? (yes/no)"
        required: false
        default: "no"

env:
  NODE_VERSION: "20"
  BUILD_DIR: "dist"
  REMOTE_DIR: "/var/www/tripgenius"
  LC_ALL: "C.UTF-8"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # 1) Build + lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build (Vite)
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-build
          path: ${{ env.BUILD_DIR }}

  # 2) Tests + coverage
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - run: npm ci

      - name: Run tests with coverage
        run: npm test -- --coverage --coverageReporters=lcov

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage

      - name: Upload to Codecov (optional)
        if: ${{ secrets.CODECOV_TOKEN != '' }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: unittests
          fail_ci_if_error: false

  # 3) Déploiement manuel (si tous les secrets SSH sont présents)
  deploy-prod:
    if: >-
      ${{ github.event_name == 'workflow_dispatch' &&
          github.event.inputs.deploy-prod == 'yes' &&
          secrets.IGLAO_SSH_KEY != '' &&
          secrets.IGLAO_USER    != '' &&
          secrets.IGLAO_HOST    != '' &&
          secrets.IGLAO_KNOWN_HOST != '' }}
    needs: test
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: site-build
          path: ${{ env.BUILD_DIR }}

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.IGLAO_SSH_KEY }}

      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.IGLAO_KNOWN_HOST }}" >> ~/.ssh/known_hosts

      - name: Rsync to server
        run: |
          rsync -avz --delete ${{ env.BUILD_DIR }}/ \
            ${{ secrets.IGLAO_USER }}@${{ secrets.IGLAO_HOST }}:${{ env.REMOTE_DIR }}

      - name: Smoke test
        run: curl -f https://tripgenius.eu || exit 1
