name: CI-CD Pipeline

on:
  # Je déclenche le workflow sur push et sur ouverture/mise à jour de PR vers main.
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Je fixe la version de Node pour garantir des builds reproductibles.
  NODE_VERSION: "20"
  # Je précise où Vite sort le build (utile pour les artefacts et Lighthouse).
  BUILD_DIR: "dist"
  # Je normalise la locale pour éviter des comportements différents selon l’OS.
  LC_ALL: "C.UTF-8"

jobs:
  # ─────────────────────────────────────────────────────────────
  # 1) Build + lint
  # ─────────────────────────────────────────────────────────────
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Je récupère le dépôt.

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }} # Je m’aligne sur NODE_VERSION défini plus haut.
          cache: npm                            # J’active le cache npm pour accélérer.

      - name: Install deps
        run: npm ci  # J’installe proprement à partir de package-lock.

      # Clés factices pour que le bundle/LHCI ne plante pas
      - name: Create .env.local for build
        run: |
          cat > .env.local << 'EOF'
          VITE_GOOGLE_PLACE_API_KEY=fake-place-key
          VITE_GOOGLE_GEMINI_AI_API_KEY=fake-gemini-key
          VITE_GOOGLE_AUTH_CLIENT_ID=fake-client.apps.googleusercontent.com
          VITE_RECAPTCHA_SITE_KEY=fake-recaptcha
          EOF
        # Je fournis des variables factices : le build Vite attend ces clés
        # même si, en CI, je n’appelle pas les services réels.

      - name: Lint & type-check
        run: npm run lint  # Je vérifie le lint et les types avant d’aller plus loin.

      - name: Build (Vite)
        run: npm run build # Je génère le bundle de production.

      - name: Upload build artefact
        uses: actions/upload-artifact@v4
        with:
          name: site-build                 # Je nomme l’artefact pour l’étape Lighthouse.
          path: ${{ env.BUILD_DIR }}       # Je pousse le contenu de dist/ tel quel.

  # ─────────────────────────────────────────────────────────────
  # 2) Tests + couverture (artefact + Codecov)
  # ─────────────────────────────────────────────────────────────
  test:
    needs: build  # Je n’exécute les tests qu’après un build concluant.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Je garde l’historique complet pour éviter les erreurs Codecov.

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - run: npm ci  # Je réinstalle pour un environnement de test propre.

      - name: Run tests (Jest + coverage)
        run: npm run test -- --coverage
        env:
          NODE_OPTIONS: "--experimental-vm-modules" # Je débloque les imports ESM côté tests.

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/  # Je conserve un artefact consultable pour le dossier.

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage/coverage-final.json
          token: ${{ secrets.CODECOV_TOKEN }} # Nécessaire si le dépôt est privé.
          flags: unittests
          fail_ci_if_error: true

  # ─────────────────────────────────────────────────────────────
  # 3) Packaging Docker (optionnel)
  # ─────────────────────────────────────────────────────────────
  package:
    needs: test  # Je ne package qu’après des tests réussis.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: |
          docker build -t tripgenius:${{ github.sha }} .
          docker image save tripgenius:${{ github.sha }} | gzip > image.tar.gz
        # Je construis une image taguée par le SHA et je l’exporte en tar.gz
        # pour pouvoir l’attacher en artefact (pratique pour debug ou déploiements manuels).

      - uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar.gz

  # ─────────────────────────────────────────────────────────────
  # 4) Déploiement Vercel (Preview)
  # ─────────────────────────────────────────────────────────────
  deploy-preprod:
    needs: package   # Je déploie en preview après build/test/package réussis.
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel (Preview)
        run: |
          npm i -g vercel
          vercel --token ${{ secrets.VERCEL_TOKEN }} --prod=false --confirm --yes
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}         # Je fournis l’organisation Vercel.
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }} # Je cible le bon projet.
        # Je déclenche un déploiement preview (non prod) pour valider avant merge.

  # ─────────────────────────────────────────────────────────────
  # 5) Lighthouse CI sur le build statique
  # ─────────────────────────────────────────────────────────────
  lighthouse:
    needs: test  # J’analyse les performances après les tests unitaires.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Download build artefact
        uses: actions/download-artifact@v4
        with:
          name: site-build
          path: ${{ env.BUILD_DIR }}  # Je récupère le build généré plus tôt.

      - name: Run Lighthouse CI
        run: npx -y @lhci/cli@latest autorun --config=.lighthouserc.json --verbose
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }} # Je publie les résultats sur la PR.

      - name: Upload LHCI report
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: .lighthouseci
          if-no-files-found: warn
          retention-days: 7  # Je conserve les rapports une semaine pour consultation.
