name: CI-CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: "20"
  BUILD_DIR: "dist"
  LC_ALL: "C.UTF-8"

# ─────────────────────────────────────────────────────────────
# 1️⃣  Build + static checks
# ─────────────────────────────────────────────────────────────
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Lint & type-check
        run: npm run lint         # eslint + tsc --noEmit

      - name: Build (Vite)
        run: npm run build        # produit ./dist

      - name: Upload build artefact
        uses: actions/upload-artifact@v4
        with:
          name: site-build
          path: ${{ env.BUILD_DIR }}

# ─────────────────────────────────────────────────────────────
# 2️⃣  Tests unitaires + couverture
# ─────────────────────────────────────────────────────────────
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - run: npm ci

      - name: Run Jest (coverage)
        run: npm run test -- --coverage
        env:
          CI: "true"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/coverage-final.json   # ✅ fichier Jest
          flags: unittests
          fail_ci_if_error: true

# ─────────────────────────────────────────────────────────────
# 3️⃣  Packaging Docker (optionnel)
# ─────────────────────────────────────────────────────────────
  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: |
          docker build -t tripgenius:${{ github.sha }} .
          docker image save tripgenius:${{ github.sha }} | gzip > image.tar.gz
      - uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar.gz

# ─────────────────────────────────────────────────────────────
# 4️⃣  Déploiement Vercel (preview)
# ─────────────────────────────────────────────────────────────
  deploy-preprod:
    needs: package
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel (Preview)
        run: |
          npm install -g vercel
          vercel --token ${{ secrets.VERCEL_TOKEN }} --prod=false --confirm --yes
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

# ─────────────────────────────────────────────────────────────
# 5️⃣  Audit Lighthouse CI + check GitHub
# ─────────────────────────────────────────────────────────────
lighthouse:
  needs: test
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: npm

    - name: Download build artefact
      uses: actions/download-artifact@v4
      with:
        name: site-build
        path: ${{ env.BUILD_DIR }}

    - name: Verify build exists
      run: |
        echo "PWD=$(pwd)"
        ls -la
        echo "Contents of $BUILD_DIR:"
        ls -la "$BUILD_DIR"

    # Chrome pour LHCI
    - uses: browser-actions/setup-chrome@v1

    - name: Install LHCI + static server
      run: npm i -g @lhci/cli@0.14.x http-server

    # Séparer collect & assert => logs plus clairs
    - name: LHCI collect
      run: lhci collect --config=.lighthouserc.json --verbose

    - name: LHCI assert
      run: lhci assert --config=.lighthouserc.json --verbose

    - name: Upload LHCI report
      uses: actions/upload-artifact@v4
      with:
        name: lighthouse-report
        path: .lighthouseci/**/*
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      # récupère le build statique
      - name: Download build artefact
        uses: actions/download-artifact@v4
        with:
          name: site-build
          path: ${{ env.BUILD_DIR }}

      - name: Install LHCI
        run: npm install -g @lhci/cli

      - name: Run Lighthouse CI
        run: lhci autorun --config=.lighthouserc.json --verbose
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Upload LHCI report
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: .lighthouseci/**/*
