name: CI‑CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      deploy-prod:
        description: "Déployer en production ? (yes/no)"
        required: false
        default: "no"

env:
  NODE_VERSION: "20"
  BUILD_DIR: "dist"
  REMOTE_DIR: "/var/www/tripgenius"          # dossier sur Iglao
  LC_ALL: "C.UTF-8"

jobs:
# ─────────────────────────────────────────────────────────────
# 1️⃣  Build + static checks (ESLint, TypeScript)
# ─────────────────────────────────────────────────────────────
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Lint & type‑check
        run: npm run lint   # -> eslint + tsc --noEmit

      - name: Build (Vite)
        run: npm run build

      - name: Upload build artefact
        uses: actions/upload-artifact@v4
        with:
          name: site-build
          path: ${{ env.BUILD_DIR }}

# ─────────────────────────────────────────────────────────────
# 2️⃣  Tests unitaires  + couverture  (Vitest + Codecov)
# ─────────────────────────────────────────────────────────────
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - run: npm ci

      - name: Run Vitest
        run: npm run test -- --coverage
        env:
          NODE_OPTIONS: "--experimental-vm-modules"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/vitest-final.json
          flags: unittests
          fail_ci_if_error: true

# ─────────────────────────────────────────────────────────────
# 3️⃣  Packaging Docker (optionnel) – trace performance image
# ─────────────────────────────────────────────────────────────
  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: |
          docker build -t tripgenius:${{ github.sha }} .
          docker image save tripgenius:${{ github.sha }} | gzip > image.tar.gz
      - uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar.gz

# ─────────────────────────────────────────────────────────────
# 4️⃣  Déploiement sur Iglao  (SSH + rsync)
# ─────────────────────────────────────────────────────────────
  deploy-prod:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.deploy-prod == 'yes'
    needs: package
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: site-build
          path: ${{ env.BUILD_DIR }}

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.IGLAO_SSH_KEY }}

      - name: Add Iglao to known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.IGLAO_KNOWN_HOST }}" >> ~/.ssh/known_hosts

      - name: Rsync to server
        run: |
          rsync -avz --delete ${{ env.BUILD_DIR }}/ \
            ${{ secrets.IGLAO_USER }}@${{ secrets.IGLAO_HOST }}:${{ env.REMOTE_DIR }}

      - name: Smoke‑test production URL
        run: curl -f https://tripgenius.eu || exit 1
